// default package
// Generated Jan 31, 2015 7:09:10 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Chucnang generated by hbm2java
 */
@Entity
@Table(name = "chucnang", catalog = "luanvan")
public class Chucnang implements java.io.Serializable {

	private Integer mayeucau;
	private Mucdo mucdo;
	private Nhomchucnang nhomchucnang;
	private Phanloaichucnang phanloaichucnang;
	private Project project;
	private Usecase usecase;
	private String motayeucau;
	private String ghichu;

	public Chucnang() {
	}

	public Chucnang(Mucdo mucdo, Nhomchucnang nhomchucnang,
			Phanloaichucnang phanloaichucnang, Project project, Usecase usecase) {
		this.mucdo = mucdo;
		this.nhomchucnang = nhomchucnang;
		this.phanloaichucnang = phanloaichucnang;
		this.project = project;
		this.usecase = usecase;
	}

	public Chucnang(Mucdo mucdo, Nhomchucnang nhomchucnang,
			Phanloaichucnang phanloaichucnang, Project project,
			Usecase usecase, String motayeucau, String ghichu) {
		this.mucdo = mucdo;
		this.nhomchucnang = nhomchucnang;
		this.phanloaichucnang = phanloaichucnang;
		this.project = project;
		this.usecase = usecase;
		this.motayeucau = motayeucau;
		this.ghichu = ghichu;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "MAYEUCAU", unique = true, nullable = false)
	public Integer getMayeucau() {
		return this.mayeucau;
	}

	public void setMayeucau(Integer mayeucau) {
		this.mayeucau = mayeucau;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MUCDOID", nullable = false)
	public Mucdo getMucdo() {
		return this.mucdo;
	}

	public void setMucdo(Mucdo mucdo) {
		this.mucdo = mucdo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "NHOMID", nullable = false)
	public Nhomchucnang getNhomchucnang() {
		return this.nhomchucnang;
	}

	public void setNhomchucnang(Nhomchucnang nhomchucnang) {
		this.nhomchucnang = nhomchucnang;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MALOAI", nullable = false)
	public Phanloaichucnang getPhanloaichucnang() {
		return this.phanloaichucnang;
	}

	public void setPhanloaichucnang(Phanloaichucnang phanloaichucnang) {
		this.phanloaichucnang = phanloaichucnang;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PROJECTID", nullable = false)
	public Project getProject() {
		return this.project;
	}

	public void setProject(Project project) {
		this.project = project;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USECASEID", nullable = false)
	public Usecase getUsecase() {
		return this.usecase;
	}

	public void setUsecase(Usecase usecase) {
		this.usecase = usecase;
	}

	@Column(name = "MOTAYEUCAU", length = 65535)
	public String getMotayeucau() {
		return this.motayeucau;
	}

	public void setMotayeucau(String motayeucau) {
		this.motayeucau = motayeucau;
	}

	@Column(name = "GHICHU")
	public String getGhichu() {
		return this.ghichu;
	}

	public void setGhichu(String ghichu) {
		this.ghichu = ghichu;
	}

}
