// default package
// Generated Jan 31, 2015 7:09:10 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * File generated by hbm2java
 */
@Entity
@Table(name = "file", catalog = "luanvan")
public class File implements java.io.Serializable {

	private Integer fileid;
	private Usecase usecase;
	private String filename;
	private String link;
	private String ghichu;

	public File() {
	}

	public File(Usecase usecase, String filename) {
		this.usecase = usecase;
		this.filename = filename;
	}

	public File(Usecase usecase, String filename, String link, String ghichu) {
		this.usecase = usecase;
		this.filename = filename;
		this.link = link;
		this.ghichu = ghichu;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "FILEID", unique = true, nullable = false)
	public Integer getFileid() {
		return this.fileid;
	}

	public void setFileid(Integer fileid) {
		this.fileid = fileid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USECASEID", nullable = false)
	public Usecase getUsecase() {
		return this.usecase;
	}

	public void setUsecase(Usecase usecase) {
		this.usecase = usecase;
	}

	@Column(name = "FILENAME", nullable = false)
	public String getFilename() {
		return this.filename;
	}

	public void setFilename(String filename) {
		this.filename = filename;
	}

	@Column(name = "LINK")
	public String getLink() {
		return this.link;
	}

	public void setLink(String link) {
		this.link = link;
	}

	@Column(name = "GHICHU")
	public String getGhichu() {
		return this.ghichu;
	}

	public void setGhichu(String ghichu) {
		this.ghichu = ghichu;
	}

}
