// default package
// Generated Jan 31, 2015 7:09:10 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Loaiactor generated by hbm2java
 */
@Entity
@Table(name = "loaiactor", catalog = "luanvan")
public class Loaiactor implements java.io.Serializable {

	private Integer loaiactorid;
	private int loai;
	private Integer trongso;
	private String ghichu;
	private String motaloaiactoer;
	private Set actors = new HashSet(0);

	public Loaiactor() {
	}

	public Loaiactor(int loai) {
		this.loai = loai;
	}

	public Loaiactor(int loai, Integer trongso, String ghichu,
			String motaloaiactoer, Set actors) {
		this.loai = loai;
		this.trongso = trongso;
		this.ghichu = ghichu;
		this.motaloaiactoer = motaloaiactoer;
		this.actors = actors;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "LOAIACTORID", unique = true, nullable = false)
	public Integer getLoaiactorid() {
		return this.loaiactorid;
	}

	public void setLoaiactorid(Integer loaiactorid) {
		this.loaiactorid = loaiactorid;
	}

	@Column(name = "LOAI", nullable = false)
	public int getLoai() {
		return this.loai;
	}

	public void setLoai(int loai) {
		this.loai = loai;
	}

	@Column(name = "TRONGSO")
	public Integer getTrongso() {
		return this.trongso;
	}

	public void setTrongso(Integer trongso) {
		this.trongso = trongso;
	}

	@Column(name = "GHICHU")
	public String getGhichu() {
		return this.ghichu;
	}

	public void setGhichu(String ghichu) {
		this.ghichu = ghichu;
	}

	@Column(name = "MOTALOAIACTOER")
	public String getMotaloaiactoer() {
		return this.motaloaiactoer;
	}

	public void setMotaloaiactoer(String motaloaiactoer) {
		this.motaloaiactoer = motaloaiactoer;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "loaiactor")
	public Set getActors() {
		return this.actors;
	}

	public void setActors(Set actors) {
		this.actors = actors;
	}

}
