// default package
// Generated Jan 31, 2015 7:09:10 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Luong generated by hbm2java
 */
@Entity
@Table(name = "luong", catalog = "luanvan")
public class Luong implements java.io.Serializable {

	private Integer luongid;
	private int bac;
	private float heso;
	private Set projects = new HashSet(0);

	public Luong() {
	}

	public Luong(int bac, float heso) {
		this.bac = bac;
		this.heso = heso;
	}

	public Luong(int bac, float heso, Set projects) {
		this.bac = bac;
		this.heso = heso;
		this.projects = projects;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "LUONGID", unique = true, nullable = false)
	public Integer getLuongid() {
		return this.luongid;
	}

	public void setLuongid(Integer luongid) {
		this.luongid = luongid;
	}

	@Column(name = "BAC", nullable = false)
	public int getBac() {
		return this.bac;
	}

	public void setBac(int bac) {
		this.bac = bac;
	}

	@Column(name = "HESO", nullable = false, precision = 12, scale = 0)
	public float getHeso() {
		return this.heso;
	}

	public void setHeso(float heso) {
		this.heso = heso;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "luong")
	public Set getProjects() {
		return this.projects;
	}

	public void setProjects(Set projects) {
		this.projects = projects;
	}

}
