// default package
// Generated Jan 31, 2015 7:09:10 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Mucluongnhanuoc generated by hbm2java
 */
@Entity
@Table(name = "mucluongnhanuoc", catalog = "luanvan")
public class Mucluongnhanuoc implements java.io.Serializable {

	private int muc;

	public Mucluongnhanuoc() {
	}

	public Mucluongnhanuoc(int muc) {
		this.muc = muc;
	}

	@Id
	@Column(name = "MUC", unique = true, nullable = false)
	public int getMuc() {
		return this.muc;
	}

	public void setMuc(int muc) {
		this.muc = muc;
	}

}
