// default package
// Generated Jan 31, 2015 7:09:10 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Nhomuc generated by hbm2java
 */
@Entity
@Table(name = "nhomuc", catalog = "luanvan")
public class Nhomuc implements java.io.Serializable {

	private Integer nhomucid;
	private String tennhom;
	private Set usecases = new HashSet(0);

	public Nhomuc() {
	}

	public Nhomuc(String tennhom) {
		this.tennhom = tennhom;
	}

	public Nhomuc(String tennhom, Set usecases) {
		this.tennhom = tennhom;
		this.usecases = usecases;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "NHOMUCID", unique = true, nullable = false)
	public Integer getNhomucid() {
		return this.nhomucid;
	}

	public void setNhomucid(Integer nhomucid) {
		this.nhomucid = nhomucid;
	}

	@Column(name = "TENNHOM", nullable = false)
	public String getTennhom() {
		return this.tennhom;
	}

	public void setTennhom(String tennhom) {
		this.tennhom = tennhom;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "nhomuc")
	public Set getUsecases() {
		return this.usecases;
	}

	public void setUsecases(Set usecases) {
		this.usecases = usecases;
	}

}
