// default package
// Generated Jan 31, 2015 7:09:10 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PhanloaiId generated by hbm2java
 */
@Embeddable
public class PhanloaiId implements java.io.Serializable {

	private int actorid;
	private int usecaseid;

	public PhanloaiId() {
	}

	public PhanloaiId(int actorid, int usecaseid) {
		this.actorid = actorid;
		this.usecaseid = usecaseid;
	}

	@Column(name = "ACTORID", nullable = false)
	public int getActorid() {
		return this.actorid;
	}

	public void setActorid(int actorid) {
		this.actorid = actorid;
	}

	@Column(name = "USECASEID", nullable = false)
	public int getUsecaseid() {
		return this.usecaseid;
	}

	public void setUsecaseid(int usecaseid) {
		this.usecaseid = usecaseid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PhanloaiId))
			return false;
		PhanloaiId castOther = (PhanloaiId) other;

		return (this.getActorid() == castOther.getActorid())
				&& (this.getUsecaseid() == castOther.getUsecaseid());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getActorid();
		result = 37 * result + this.getUsecaseid();
		return result;
	}

}
