// default package
// Generated Jan 31, 2015 7:09:10 PM by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Phanloai generated by hbm2java
 */
@Entity
@Table(name = "phanloai", catalog = "luanvan")
public class Phanloai implements java.io.Serializable {

	private PhanloaiId id;
	private Actor actor;
	private Usecase usecase;
	private int vaitro;

	public Phanloai() {
	}

	public Phanloai(PhanloaiId id, Actor actor, Usecase usecase, int vaitro) {
		this.id = id;
		this.actor = actor;
		this.usecase = usecase;
		this.vaitro = vaitro;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "actorid", column = @Column(name = "ACTORID", nullable = false)),
			@AttributeOverride(name = "usecaseid", column = @Column(name = "USECASEID", nullable = false)) })
	public PhanloaiId getId() {
		return this.id;
	}

	public void setId(PhanloaiId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ACTORID", nullable = false, insertable = false, updatable = false)
	public Actor getActor() {
		return this.actor;
	}

	public void setActor(Actor actor) {
		this.actor = actor;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USECASEID", nullable = false, insertable = false, updatable = false)
	public Usecase getUsecase() {
		return this.usecase;
	}

	public void setUsecase(Usecase usecase) {
		this.usecase = usecase;
	}

	@Column(name = "VAITRO", nullable = false)
	public int getVaitro() {
		return this.vaitro;
	}

	public void setVaitro(int vaitro) {
		this.vaitro = vaitro;
	}

}
