// default package
// Generated Jan 31, 2015 7:09:10 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Phanloaichucnang generated by hbm2java
 */
@Entity
@Table(name = "phanloaichucnang", catalog = "luanvan")
public class Phanloaichucnang implements java.io.Serializable {

	private Integer maloai;
	private String tenloai;
	private Set chucnangs = new HashSet(0);

	public Phanloaichucnang() {
	}

	public Phanloaichucnang(String tenloai) {
		this.tenloai = tenloai;
	}

	public Phanloaichucnang(String tenloai, Set chucnangs) {
		this.tenloai = tenloai;
		this.chucnangs = chucnangs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "MALOAI", unique = true, nullable = false)
	public Integer getMaloai() {
		return this.maloai;
	}

	public void setMaloai(Integer maloai) {
		this.maloai = maloai;
	}

	@Column(name = "TENLOAI", nullable = false)
	public String getTenloai() {
		return this.tenloai;
	}

	public void setTenloai(String tenloai) {
		this.tenloai = tenloai;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "phanloaichucnang")
	public Set getChucnangs() {
		return this.chucnangs;
	}

	public void setChucnangs(Set chucnangs) {
		this.chucnangs = chucnangs;
	}

}
