// default package
// Generated Jan 31, 2015 7:09:10 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Phichucnang generated by hbm2java
 */
@Entity
@Table(name = "phichucnang", catalog = "luanvan")
public class Phichucnang implements java.io.Serializable {

	private Integer mayeucau;
	private Project project;
	private String motayeucau;

	public Phichucnang() {
	}

	public Phichucnang(Project project) {
		this.project = project;
	}

	public Phichucnang(Project project, String motayeucau) {
		this.project = project;
		this.motayeucau = motayeucau;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "MAYEUCAU", unique = true, nullable = false)
	public Integer getMayeucau() {
		return this.mayeucau;
	}

	public void setMayeucau(Integer mayeucau) {
		this.mayeucau = mayeucau;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PROJECTID", nullable = false)
	public Project getProject() {
		return this.project;
	}

	public void setProject(Project project) {
		this.project = project;
	}

	@Column(name = "MOTAYEUCAU", length = 65535)
	public String getMotayeucau() {
		return this.motayeucau;
	}

	public void setMotayeucau(String motayeucau) {
		this.motayeucau = motayeucau;
	}

}
