// default package
// Generated Jan 31, 2015 7:09:10 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Usecase generated by hbm2java
 */
@Entity
@Table(name = "usecase", catalog = "luanvan")
public class Usecase implements java.io.Serializable {

	private Integer usecaseid;
	private Bmt bmt;
	private Mucdo mucdo;
	private Mucdocanthiet mucdocanthiet;
	private Nhomuc nhomuc;
	private Project project;
	private String nameofuc;
	private String motauc;
	private String cauhoi;
	private int tinhtien;
	private Set files = new HashSet(0);
	private Set phanloais = new HashSet(0);
	private Set chucnangs = new HashSet(0);

	public Usecase() {
	}

	public Usecase(Bmt bmt, Mucdo mucdo, Mucdocanthiet mucdocanthiet,
			Nhomuc nhomuc, Project project, String nameofuc, String motauc,
			int tinhtien) {
		this.bmt = bmt;
		this.mucdo = mucdo;
		this.mucdocanthiet = mucdocanthiet;
		this.nhomuc = nhomuc;
		this.project = project;
		this.nameofuc = nameofuc;
		this.motauc = motauc;
		this.tinhtien = tinhtien;
	}

	public Usecase(Bmt bmt, Mucdo mucdo, Mucdocanthiet mucdocanthiet,
			Nhomuc nhomuc, Project project, String nameofuc, String motauc,
			String cauhoi, int tinhtien, Set files, Set phanloais, Set chucnangs) {
		this.bmt = bmt;
		this.mucdo = mucdo;
		this.mucdocanthiet = mucdocanthiet;
		this.nhomuc = nhomuc;
		this.project = project;
		this.nameofuc = nameofuc;
		this.motauc = motauc;
		this.cauhoi = cauhoi;
		this.tinhtien = tinhtien;
		this.files = files;
		this.phanloais = phanloais;
		this.chucnangs = chucnangs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "USECASEID", unique = true, nullable = false)
	public Integer getUsecaseid() {
		return this.usecaseid;
	}

	public void setUsecaseid(Integer usecaseid) {
		this.usecaseid = usecaseid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "BMTID", nullable = false)
	public Bmt getBmt() {
		return this.bmt;
	}

	public void setBmt(Bmt bmt) {
		this.bmt = bmt;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MUCDOID", nullable = false)
	public Mucdo getMucdo() {
		return this.mucdo;
	}

	public void setMucdo(Mucdo mucdo) {
		this.mucdo = mucdo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MUCDOCANTHIETID", nullable = false)
	public Mucdocanthiet getMucdocanthiet() {
		return this.mucdocanthiet;
	}

	public void setMucdocanthiet(Mucdocanthiet mucdocanthiet) {
		this.mucdocanthiet = mucdocanthiet;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "NHOMUCID", nullable = false)
	public Nhomuc getNhomuc() {
		return this.nhomuc;
	}

	public void setNhomuc(Nhomuc nhomuc) {
		this.nhomuc = nhomuc;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PROJECTID", nullable = false)
	public Project getProject() {
		return this.project;
	}

	public void setProject(Project project) {
		this.project = project;
	}

	@Column(name = "NAMEOFUC", nullable = false)
	public String getNameofuc() {
		return this.nameofuc;
	}

	public void setNameofuc(String nameofuc) {
		this.nameofuc = nameofuc;
	}

	@Column(name = "MOTAUC", nullable = false, length = 65535)
	public String getMotauc() {
		return this.motauc;
	}

	public void setMotauc(String motauc) {
		this.motauc = motauc;
	}

	@Column(name = "CAUHOI", length = 65535)
	public String getCauhoi() {
		return this.cauhoi;
	}

	public void setCauhoi(String cauhoi) {
		this.cauhoi = cauhoi;
	}

	@Column(name = "TINHTIEN", nullable = false)
	public int getTinhtien() {
		return this.tinhtien;
	}

	public void setTinhtien(int tinhtien) {
		this.tinhtien = tinhtien;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usecase")
	public Set getFiles() {
		return this.files;
	}

	public void setFiles(Set files) {
		this.files = files;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usecase")
	public Set getPhanloais() {
		return this.phanloais;
	}

	public void setPhanloais(Set phanloais) {
		this.phanloais = phanloais;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usecase")
	public Set getChucnangs() {
		return this.chucnangs;
	}

	public void setChucnangs(Set chucnangs) {
		this.chucnangs = chucnangs;
	}

}
