// default package
// Generated Jan 31, 2015 7:09:10 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * XephangnhomId generated by hbm2java
 */
@Embeddable
public class XephangnhomId implements java.io.Serializable {

	private int projectid;
	private int hesomoitruongid;

	public XephangnhomId() {
	}

	public XephangnhomId(int projectid, int hesomoitruongid) {
		this.projectid = projectid;
		this.hesomoitruongid = hesomoitruongid;
	}

	@Column(name = "PROJECTID", nullable = false)
	public int getProjectid() {
		return this.projectid;
	}

	public void setProjectid(int projectid) {
		this.projectid = projectid;
	}

	@Column(name = "HESOMOITRUONGID", nullable = false)
	public int getHesomoitruongid() {
		return this.hesomoitruongid;
	}

	public void setHesomoitruongid(int hesomoitruongid) {
		this.hesomoitruongid = hesomoitruongid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof XephangnhomId))
			return false;
		XephangnhomId castOther = (XephangnhomId) other;

		return (this.getProjectid() == castOther.getProjectid())
				&& (this.getHesomoitruongid() == castOther.getHesomoitruongid());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getProjectid();
		result = 37 * result + this.getHesomoitruongid();
		return result;
	}

}
