// default package
// Generated Jan 31, 2015 7:09:10 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * XephangkythuatId generated by hbm2java
 */
@Embeddable
public class XephangkythuatId implements java.io.Serializable {

	private int projectid;
	private int hesokythuatid;

	public XephangkythuatId() {
	}

	public XephangkythuatId(int projectid, int hesokythuatid) {
		this.projectid = projectid;
		this.hesokythuatid = hesokythuatid;
	}

	@Column(name = "PROJECTID", nullable = false)
	public int getProjectid() {
		return this.projectid;
	}

	public void setProjectid(int projectid) {
		this.projectid = projectid;
	}

	@Column(name = "HESOKYTHUATID", nullable = false)
	public int getHesokythuatid() {
		return this.hesokythuatid;
	}

	public void setHesokythuatid(int hesokythuatid) {
		this.hesokythuatid = hesokythuatid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof XephangkythuatId))
			return false;
		XephangkythuatId castOther = (XephangkythuatId) other;

		return (this.getProjectid() == castOther.getProjectid())
				&& (this.getHesokythuatid() == castOther.getHesokythuatid());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getProjectid();
		result = 37 * result + this.getHesokythuatid();
		return result;
	}

}
