package vn.com.luanvan.model;

// default package
// Generated Jan 31, 2015 7:09:10 PM by Hibernate Tools 4.3.1

import java.sql.Blob;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "tracnghiem")
public class User implements java.io.Serializable {

	private String email;
	private String password;
	private String name;
	private Blob avatar;

	public User() {
	}

	public User(String email, String password, String name, Blob avatar) {
		this.email = email;
		this.password = password;
		this.name = name;
		this.avatar = avatar;
	}

	@Id
	@Column(name = "EMAIL", unique = true, nullable = false, length = 100)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "MATKHAU", nullable = false, length = 100)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}
/*
	@Column(name = "ENABLED", nullable = false, precision = 1, scale = 0)
	public boolean isEnabled() {
		return this.enabled;
	}

	public void setEnabled(boolean enabled) {
		this.enabled = enabled;
	}
*/
	
	@Column(name = "HOTEN", nullable = true, length=100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}
	
	@Column(name = "AVATAR", nullable = true)
	public Blob getAvatar() {
		return this.avatar;
	}

	public void setAvatar(Blob avatar) {
		this.avatar = avatar;
	}

	
}
